services:
  wallet_db:
    image: postgres:15.2-alpine
    container_name: wallet_db
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_DB=wallet_db
    command: postgres -c 'max_connections=200'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  django:
    container_name: wallet_django
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "
      python /usr/src/wallet/manage.py migrate --noinput &&
      python /usr/src/wallet/manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/usr/src/wallet
    ports:
      - 8000:8000
    depends_on:
      - wallet_db
    restart: always
    env_file:
      - ./config/.env

volumes:
  postgres_data:
