# Generated by Django 4.2 on 2023-04-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('eth', 'Eth')], help_text='Валюта', max_length=20)),
                ('public_key', models.CharField(help_text='Публичный ĸлюч(адрес)', max_length=255)),
                ('private_key', models.CharField(help_text='Приватный ĸлюч', max_length=255)),
            ],
        ),
    ]
