# Generated by Django 4.2 on 2023-04-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(help_text='Приватный ĸлюч', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='public_key',
            field=models.CharField(help_text='Публичный ĸлюч(адрес)', max_length=255, unique=True),
        ),
    ]
